#!/usr/bin/env bash

#Set up autograder files 

cp /autograder/submission/assignment3.py /autograder/source/assignment3.py

cd /autograder/source

python3 run_tests.py > /autograder/results/results.json
