#!/usr/bin/env bash

#Set up autograder files 

cp /autograder/submission/assignment2.py /autograder/source/assignment2.py

cd /autograder/source

python3 run_tests.py > /autograder/results/results.json
